### ISSUE TITLE
Computational cost governing after step 5000

### ISSUE THREAD

**Issue by TLB-MISS** [bytedance/MVDream-threestudio#12]
First of all, thank you for the great work.

After step 5000, GPU memory consumption increases rapidly. Which part dominates this? I want to reduce memory.

Thanks

**Comment by seasonSH** [comment]
The only thing changed is the rendering resolution. You may want to reduce it.

**Comment by TLB-MISS** [comment]
@seasonSH 

Thanks for your relpy!

This is a completely different topic, but do you have any ideas on [this](https://github.com/bytedance/MVDream-threestudio/issues/1#issuecomment-1760978072)?
