### ISSUE TITLE
MaxRetryError(“HTTPSConnectionPool(host=‘huggingface.co', port=443)

### ISSUE THREAD

**Issue by HuntZhaozq** [bytedance/MVDream-threestudio#13]
运行python launch.py后遇到下面问题，电脑是ping不通huggingface.co的，请问如何解决？
MaxRetryError(“HTTPSConnectionPool(host=‘huggingface.co', port=443): Max retries exceeded with url : /laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin

**Comment by yanjk3** [comment]
You can use vpn to download the checkpoint ``sd-v2.1-base-4view.pt``manually.
And then you should modify the ``pretrained=version`` [here](https://github.com/bytedance/MVDream/blob/main/mvdream/ldm/modules/encoders/modules.py#L147C110-L147C110) to ``pretrained=False``
Last, when running python launch,py, you can set ``--ckpt_path`` as your local path to the sd-v2.1-base-4view.pt.

**Comment by HuntZhaozq** [comment]
@yanjk3 Thanks. It runs without the above error by setting above. But I meet another error:
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Epoch 0 :
