### ISSUE TITLE
Some example prompts or pretrained models

### ISSUE THREAD

**Issue by zhengyuf** [bytedance/MVDream-threestudio#4]
Hi,

thanks for the great work!
Would it be possible to share some well-performing prompts (such as the ones used for the teasers), or some pretrained models?

**Comment by seasonSH** [comment]
I have added the links to the gallery on the README, you can fine the prompts either in the comparison results or the additional gallery

**Comment by zhengyuf** [comment]
Thank you for the quick reply!
