### ISSUE TITLE
Why MVdream is way more faster than dreamfusion-sd?

### ISSUE THREAD

**Issue by jk4011** [bytedance/MVDream-threestudio#6]
Thank you for your wonderful project. 

I've observed that MVdream's coarse stage is approximately 2.6x faster than dreamfusion-sd when using 64x64 guidance and an 8 batch size. 

Could the speed difference be primarily due to soft-shading?

**Comment by seasonSH** [comment]
Because in the coarse stage, the computation cost mainly comes from the diffusion model. And the cost of MVDream generating 4 images (256) is about the same as SD generating 1 image (512).

**Comment by jk4011** [comment]
Thank you for kind comment!
